# Generated by Django 2.2.3 on 2024-04-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='estado',
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='piso',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tlf',
            field=models.PositiveIntegerField(max_length=15),
        ),
    ]
