# Generated by Django 2.2.3 on 2024-04-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20240406_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='piso',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tlf',
            field=models.CharField(max_length=9),
        ),
    ]
