# Generated by Django 2.2.3 on 2024-04-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20240406_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='piso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
