# Generated by Django 2.2.3 on 2024-04-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(default='Direccion predeterminada', max_length=200),
        ),
    ]
